// <auto-generated />
using System;
using EdenlandAPI.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EdenlandAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200719153448_FirstModel")]
    partial class FirstModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.BeauticianModel", b =>
                {
                    b.Property<int>("BeauticianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeauticianId");

                    b.ToTable("B_Beautician");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.BeauticiansTreatmentsModel", b =>
                {
                    b.Property<int>("BeauticianTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeauticianId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("BeauticianTreatmentId");

                    b.HasIndex("BeauticianId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("B_ BeauticiansTreatments");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.TreatmentModel", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceTreatment")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("TimeSpanTreatment")
                        .HasColumnType("time");

                    b.HasKey("TreatmentId");

                    b.ToTable("B_Treatments");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("QuantityInPackage")
                        .HasColumnType("smallint");

                    b.Property<byte>("UnitOfMeasurement")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.BeauticiansTreatmentsModel", b =>
                {
                    b.HasOne("EdenlandAPI.Domain.Models.Beautician.BeauticianModel", "Beauticians")
                        .WithMany("Treatments")
                        .HasForeignKey("BeauticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EdenlandAPI.Domain.Models.Beautician.TreatmentModel", "Treatments")
                        .WithMany("Beauticians")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Product", b =>
                {
                    b.HasOne("EdenlandAPI.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
