// <auto-generated />
using System;
using EdenlandAPI.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EdenlandAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.BeauticianModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("B_Beautician");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            FirstName = "Andżelika",
                            LastName = "Wągrowiec"
                        },
                        new
                        {
                            Id = 101,
                            FirstName = "Dorota",
                            LastName = "Źdźbło"
                        });
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.BeauticiansTreatmentsModel", b =>
                {
                    b.Property<int>("BeauticianId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("BeauticianId", "TreatmentId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("B_ BeauticiansTreatments");

                    b.HasData(
                        new
                        {
                            BeauticianId = 100,
                            TreatmentId = 110
                        },
                        new
                        {
                            BeauticianId = 100,
                            TreatmentId = 111
                        },
                        new
                        {
                            BeauticianId = 101,
                            TreatmentId = 110
                        });
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.TreatmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceTreatment")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("TimeSpanTreatment")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("B_Treatments");

                    b.HasData(
                        new
                        {
                            Id = 110,
                            DescriptionTreatment = "Polewanie z konewki",
                            NameTreatment = "Bicze wodne",
                            PriceTreatment = 120.0,
                            TimeSpanTreatment = new TimeSpan(0, 0, 10, 10, 0)
                        },
                        new
                        {
                            Id = 111,
                            DescriptionTreatment = "Gorzka czekolada z dodatkiem olejków ukoi Twoje zmysły i przyniesie ukojenie",
                            NameTreatment = "Masaż czekoladowy",
                            PriceTreatment = 220.0,
                            TimeSpanTreatment = new TimeSpan(0, 0, 30, 10, 0)
                        });
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("QuantityInPackage")
                        .HasColumnType("smallint");

                    b.Property<byte>("UnitOfMeasurement")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Beautician.BeauticiansTreatmentsModel", b =>
                {
                    b.HasOne("EdenlandAPI.Domain.Models.Beautician.BeauticianModel", "Beautician")
                        .WithMany("Treatments")
                        .HasForeignKey("BeauticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EdenlandAPI.Domain.Models.Beautician.TreatmentModel", "Treatment")
                        .WithMany("Beauticians")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdenlandAPI.Domain.Models.Product", b =>
                {
                    b.HasOne("EdenlandAPI.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
